dashevo/js-dapi-client

package-lock.json
package.json
src/MNDiscovery/index.js
src/index.js

This fixes two problems:
- a bug in MNList filtering
- a bug in checking if exlcudedIps is already filled. Before this new check, it could happen that exlcudedIps existed, but was not an array, which would lead the next instruction with .slice() to cause an error.

Bugfix: fix getting ip in MNList filtering

---

README.md

Add badges and expand descriptions.
Also, not sure (since they aren't in sync) if we should use:
1. Most recent Github release: ![](https://img.shields.io/github/release/dashevo/dapi-client.svg), or
2. Most recent Github tag: ![](https://img.shields.io/github/tag-date/dashevo/dapi-client.svg)
Currently, the release badge is there, but it looks like the tag badge would match npm, so open to discussion...

Readme description and badge updates 

---

package-lock.json
package.json
src/index.js
test/bootstrap.js
test/src/index.js

Introduce `updateState` API endpoint
Remove `sendRawTransition` API endpoint

Introduce `updateState` API endpoint

---

.editorconfig
package-lock.json
package.json
src/index.js
test/src/index.js

feat: fetchIdentity endpoint

---

.travis.yml
scripts/travis-deploy.sh

This is based on #106, will rebase when that gets merged

chore: Update Travis config and Node versions

---

package-lock.json
package.json
src/index.js

BREAKING CHANGE: Removed unsupported generate endpoint

feat: introduce `generateToAddress` endpoint

---

docs/usage/utils/subscribeToTransactionsWithProofs.md

This adds a documentation usage for the subscribeToTransactionsWithProofs method.
- updated subscribeToTransactionsWithProofs doc

docs: subscribeToTransactionsWithProofs

---

package-lock.json
package.json

Updating version to make a dev release
Updating version to make a dev release
Not required
None

chore: update version to 0.13.0-dev.3

---

index.d.ts
src/index.js

In DashJS, [here](https://github.com/dashevo/DashJS/blob/master/typings/dapi-client.d.ts), we have locally some typings. 
In order to be able to remove them from there, and as 0.13 will not contain #140, this PR propose to add them in 0.13.
copy/pasted typings from DashJS.
N/A
None

docs: add typing

---

test/integration/SMLProvider/SimplifiedMasternodeListProvider.spec.js

`getSimplifiedMNList` tests are failing on slow machines (Travis CI) due to timeout
Increased timeout for `getSimplifiedMNList` tests
Tests are running in CI
None

test: increase timeout for `getSimplifiedMNList` test

---

package-lock.json
package.json

To work properly, we need to update dapi-grpc to 0.14
Update dapi-grpc dependency to 0.14

chore: update dapi-grpc to 0.14.0-dev.1

---

package-lock.json
package.json

Bumped version to 0.14.0-dev.5

chore: bump version to 0.14.0-dev.5

---

src/MNDiscovery/ListMNDiscovery.js
src/MNDiscovery/MasternodeListProvider.js
src/MNDiscovery/index.js
src/index.js
src/transport/JsonRpcTransport.js
test/integration/retries.js

Retry logic doesn't work for MN discovery
Use `JsonRpcTransport` with retry logic instead of `RPCClient` inside `MasternodeListProvider`
With functional test
None

fix: retries don't work for MN discovery

---

src/transport/GrpcTransport.js

An incorrect error was thrown in GrpcTransport if there are no masternodes available
Correct error added

fix: calling method `getIp` of `undefined`

---

package-lock.json
package.json
src/MNDiscovery/MasternodeListProvider.js
test/fixtures/mnList.js

The network option is required for `SimplifiedMNListDiff`
- Pass `testnet` to `SimplifiedMNListDiff` constructor
- Remove unused code
- Update dashcore-lib to `0.18.7`
None
None

fix: network is not set to `SimplifiedMNListDiff`

---

package-lock.json
package.json

Update `dashcore-lib` to `0.18.10` containing hot-fix for `Network` object being used
Updated `dashcore-lib` to `0.18.10`
Tests.
None.

feat: update `dashcore-lib` to `0.18.10`

---

package-lock.json
package.json

dashcore-lib doesn't handle networks properly
Update dashcore-lib
None

feat: update `dashcore-lib` to `0.18.11`

---

package-lock.json
package.json

Updating `dashcore-lib` to a version containing latest hot-fixes
- Updated `dashcore-lib` to a version of `0.18.11`
Unit tests.
None.

feat: update `dashcore-lib` to 0.18.11

---

package-lock.json
package.json

Updated version for a release
Updated version for a release to `0.14.0-dev.7`
Units.
None

chore: update version to 0.14.0-dev.7

---

README.md
docs/README.md

Brings readme into better [standard-readme](https://github.com/RichardLitt/standard-readme) compliance. Also aligns with changes previously made on master for 0.13.
N/A
N/A

docs: readme standard updates

---

README.md
docs/_sidebar.md
docs/getting-started/quickstart.md
docs/usage/application/applyStateTransition.md
docs/usage/application/getDataContract.md
docs/usage/application/getDocuments.md
docs/usage/application/getIdentity.md
docs/usage/application/getIdentityByFirstPublicKey.md
docs/usage/application/getIdentityIdByFirstPublicKey.md
docs/usage/payment/getBestBlockHash.md
docs/usage/payment/getBlockHash.md
docs/usage/payment/getUTXO.md
docs/usage/utils/getMnListDiff.md
docs/usage/utils/subscribeToTransactionsWithProofs.md

The dapi-client rewrite as part of 0.14 requires some documentation changes
N/A
N/A

docs: 0.14 updates

---

package-lock.json
package.json

To make a new pre-release we need to bump version
Version bumped to 0.14.0-dev.8
None

chore: bump version to 0.14.0-dev.8

---

package-lock.json
package.json

Use new version of DAPI gRPC
Update DAPI gRPC to 0.15.0-dev.2
With tests
None

feat: update DAPI gRPC to 0.15.0-dev.2

---

karma.conf.js
package-lock.json
package.json
webpack.config.js

Update Dashcore lib to latest version.
Update Dashcore Lib dependency to 0.19.1 and fix build for browsers.
Running tests and build
None

feat: update Dashcore Lib to 0.19.1

---

package-lock.json
package.json

Need to update dashcore-lib to 0.19.2
dashcore-lib updated to 0.19.2
Unit tests
None

feat: update dashcore-lib to 0.19.2

---

package-lock.json
package.json

Need to revert dashcore-lib to 0.18.11
dashcore-lib reverted to 0.18.11
Unit tests
None

feat: revert dashcore-lib to 0.18.11

---

package-lock.json
package.json

To make a new pre-release we need to bump version
Version bumped to 0.15.0-dev.4
Unit tests
None

chore: bump version to 0.15.0-dev.4

---

lib/methods/core/broadcastTransactionFactory.js
lib/methods/core/getBlockByHashFactory.js
lib/methods/core/getBlockByHeightFactory.js
lib/methods/core/getStatusFactory.js
lib/methods/core/getTransactionFactory.js
lib/methods/core/subscribeToTransactionsWithProofsFactory.js
lib/methods/platform/broadcastStateTransitionFactory.js
lib/methods/platform/getDataContractFactory.js
lib/methods/platform/getDocumentsFactory.js
lib/methods/platform/getIdentityByFirstPublicKeyFactory.js
lib/methods/platform/getIdentityFactory.js
lib/methods/platform/getIdentityIdByFirstPublicKeyFactory.js
package-lock.json
package.json
test/integration/methods/core/CoreMethodsFacade.spec.js
test/integration/methods/platform/PlatformMethodsFacade.spec.js
test/unit/methods/core/broadcastTransactionFactory.spec.js
test/unit/methods/core/getBlockByHashFactory.spec.js
test/unit/methods/core/getBlockByHeightFactory.spec.js
test/unit/methods/core/getStatusFactory.spec.js
test/unit/methods/core/getTransactionFactory.spec.js
test/unit/methods/core/subscribeToTransactionsWithProofsFactory.spec.js
test/unit/methods/platform/broadcastStateTransitionFactory.spec.js
test/unit/methods/platform/getDataContractFactory.spec.js
test/unit/methods/platform/getDocumentsFactory.spec.js
test/unit/methods/platform/getIdentityByFirstPublicKeyFactory.spec.js
test/unit/methods/platform/getIdentityFactory.spec.js
test/unit/methods/platform/getIdentityIdByFirstPublicKeyFactory.spec.js

Update DAPI gRPC to 0.15
Update DAPI gRPC to 0.15
With tests
None

feat: update DAPI gRPC to 0.15

---

README.md

Incorrect links in readme
Update links
N/A
N/A

docs: more URL fixes

---

CHANGELOG.md
lib/methods/platform/PlatformMethodsFacade.js
lib/methods/platform/getIdentitiesByPublicKeyHashesFactory.js
lib/methods/platform/getIdentityIdsByPublicKeyHashesFactory.js
package-lock.json
package.json
test/unit/methods/platform/getIdentitiesByPublicKeyHashesFactory.spec.js
test/unit/methods/platform/getIdentityIdsByPublicKeyHashesFactory.spec.js

Adding  `getIdentitiesByPublicKeyHashes` method
Added  `getIdentitiesByPublicKeyHashes` method
None.

feat: add `getIdentitiesByPublicKeyHashes` method

---

package-lock.json
package.json

Updated version
Updated version

chore: bump version to 0.16.0-dev.1

---

package-lock.json
package.json

chore: update `dapi-grpc`

---

lib/methods/core/getBlockByHeightFactory.js
package-lock.json

`@grpc/proto-loader` is using original (not fixed) version of `protobufjs`
```sh
❯ npm ls protobufjs
@dashevo/dapi-client@0.16.0-dev.3 /Users/ivanshumkov/Projects/dashevo/dapi-client
└─┬ @dashevo/dapi-grpc@0.16.0-dev.3
├─┬ @dashevo/grpc-common@0.3.1
│ └─┬ @grpc/proto-loader@0.5.5
│   └── protobufjs@6.10.1 
├─┬ grpc@1.24.3
│ └── protobufjs@5.0.3 
└── protobufjs@6.10.1  (github:jawid-h/protobuf.js#264b99b2ab6e097ff5350a57055d754d44d8e703)
```
Removed package lock and `node_modules` and install them from scratch.
```sh
npm ls protobufjs
```
None

fix: proto-loader is using not patched version of pbjs

---

package-lock.json
package.json

chore(release): bump version to 0.16.0-dev.5

---

package-lock.json
package.json

chore: update dpp to dev-8

---

package-lock.json
package.json

chore(release): dapi-client 0.16.0-dev.7

---

package-lock.json
package.json

feat: update dashcore-lib to 0.19.5
dpp updated to 0.17.0-dev.2, dashcore-lib to 0.19.5
Tests
No

feat: update dpp to 0.17.0-dev.2, dashcore-lib to 0.19.5

---

package-lock.json
package.json

chore: update dashcore-lib and dpp to the latest versions

---

package-lock.json
package.json

chore: update dpp to the latest version

---

package-lock.json
package.json

updated `dpp` and `dashcore-lib`
update `dpp` and `dashcore-lib`

feat: update `dpp` and `dashcore-lib`

---

package-lock.json
package.json

bump version to 0.17.0-dev.4
bump version to 0.17.0-dev.4

chore: bump version to 0.17.0-dev.4

---

lib/DAPIClient.js
lib/networkConfigs.js
test/unit/DAPIClient.spec.js

Use the testnet network by default
Added testnet seeds and use testnet network by default
With tests

feat: introduce testnet network

---

lib/SimplifiedMasternodeListProvider/SimplifiedMasternodeListProvider.js
test/integration/SMLProvider/SimplifiedMasternodeListProvider.spec.js

SML unhandled error on blockchain reorg
Tests
No

fix: SML unhandled error on blockchain reorg

---

package-lock.json
package.json

Fixing an issue in dashcore-lib: merkleRootQuorums from the diff doesn’t match calculated quorum root after diff is applied
- Updated `dashcore-lib`
On testnet.
None.

fix: merkleRootQuorums from the diff doesn’t match calculated quorum root after diff is applied

---

CHANGELOG.md
package-lock.json
package.json

Updating to v17.1
- Updated changelog
- Bumped version
None.
None.

chore(release): update changelog and bump version 0.17.1

---

CHANGELOG.md
package-lock.json
package.json

Updating to v17.2
- Updated changelog
- Bumped version
None.
None.

chore(release): update changelog and bump version 0.17.2

---

lib/methods/platform/broadcastStateTransitionFactory.js

Removing timeout option that has been introduced in #219 
- removed `timeout: undefined` 
None.

chore: remove temporary `timeout` option from `broadcastStateTransition`

---

lib/DAPIClient.js
lib/methods/platform/waitForStateTransitionResultFactory.js
lib/transport/GrpcTransport.js
test/unit/methods/platform/waitForStateTransitionResultFactory.spec.js

Banning address if waiting for state transition result wasn't successfull
Add special "noBanOnDeadlineExceeded" option to GrpcTransport#request
It wasn't
None

feat: add "throwDeadlineExceeded" option for waitForStateTransitionResult

---

package-lock.json
package.json

chore: bump version to 0.18-dev.2

---

package-lock.json
package.json

update dapi-grpc to 0.18.0-dev.3
No

feat: update dapi-grpc to 0.18.0-dev.3

---

package-lock.json
package.json

BLS library was throwing an error inside of the `uncaughtException` handler causing a Node process crash.
- updated `dashcore-lib`
Local runs
None.

fix: BLS was throwing an error inside `uncaughtException` handler

---

package-lock.json
package.json

updated dashcore-lib to 0.19.21, dpp to 0.18.0-dev.2

feat: update dashcore-lib to 0.19.21

---

package-lock.json
package.json
test/unit/methods/core/getStatusFactory.spec.js

Update getStatus response to support https://github.com/dashevo/dapi/pull/347
- Updated dapi-grpc library to 0.19.0-dev.1
- Updated getStatus unit test
- getStatus response format is changed. See https://github.com/dashevo/dapi-grpc/blob/v0.19-dev/protos/core/v0/core.proto#L19-L86

feat!: update getStatus response

---

lib/methods/core/getStatusFactory.js
test/integration/methods/core/CoreMethodsFacade.spec.js
test/unit/methods/core/getStatusFactory.spec.js

The getStatus response contains numbers instead of labels for enums 
Replace numbers with lables in core status response
With unit test
None

fix: core status includes numbers instead of labels for enums

---

CHANGELOG.md
package-lock.json
package.json

Release 0.19.0
- Update changelog
- Bump version to 0.19.0
None
None

chore(release): update changelog and bump version 0.19.0

---

lib/methods/core/getStatusFactory.js
test/unit/methods/core/getStatusFactory.spec.js

`getStatus` handler response was returning buffers as base64 encoded strings
- manually constructed response
Unit tests
None.

fix: `getStatus` reponse was returning buffers as Base64 encoded strings

---

package-lock.json
package.json

Update dpp to a bugfix release
Updated dpp
None

chore: update dpp to 0.19.2

---

CHANGELOG.md
package-lock.json
package.json

DPP not serializing some STs properly
Update dpp
Run the tests
None

chore(release): 0.19.2

---

package-lock.json
package.json

Need to bump version to make a new release
The version bumped to 0.20.0-dev.3
Tests
No

chore: bump version to 0.20.0-dev.3

---

lib/methods/core/CoreMethodsFacade.js
lib/methods/core/getTransaction/GetTransactionResponse.js
lib/methods/core/getTransaction/getTransactionFactory.js
lib/methods/errors/NotFoundError.js
lib/methods/errors/ResponseError.js
package-lock.json
package.json
test/integration/methods/core/CoreMethodsFacade.spec.js
test/unit/methods/core/getTransaction/GetTransactionResponse.spec.js
test/unit/methods/core/getTransaction/getTransactionFactory.spec.js
test/unit/methods/core/getTransactionFactory.spec.js

Add additional metadata for core `getTransaction` response
- Added response class for core `getTransaction` method
Core method `getTransaction` responds with response class instead of plain data
Core method `getTransaction` throws a NotFound error in case if the transaction is not present.

feat!: get transaction metadata

---

lib/methods/platform/getDataContract/getDataContractFactory.js
lib/methods/platform/getIdentity/getIdentityFactory.js
package-lock.json
package.json
test/unit/methods/platform/getDataContract/getDataContractFactory.spec.js
test/unit/methods/platform/getIdentitiy/getIdentityFactory.spec.js

To make methods more consistent, `getDataContract` and `getIdentity` platform methods should throw NotFoundError if data is not found
`getDataContract` and `getIdentity` platform methods now throws NotFoundErrorinstead of null result
Unit tests
`getDataContract` and `getIdentity` platform methods throws NotFoundError if data is not found

feat!: throw NotFoundError if data is not found

---

lib/methods/platform/getDataContract/GetDataContractResponse.js
lib/methods/platform/getDataContract/getDataContractFactory.js
lib/methods/platform/getDocuments/GetDocumentsResponse.js
lib/methods/platform/getDocuments/getDocumentsFactory.js
lib/methods/platform/getIdentitiesByPublicKeyHashes/GetIdentitiesByPublicKeyHashesResponse.js
lib/methods/platform/getIdentitiesByPublicKeyHashes/getIdentitiesByPublicKeyHashesFactory.js
lib/methods/platform/getIdentity/GetIdentityResponse.js
lib/methods/platform/getIdentity/getIdentityFactory.js
lib/methods/platform/getIdentityIdsByPublicKeyHashes/GetIdentityIdsByPublicKeyHashesResponse.js
lib/methods/platform/getIdentityIdsByPublicKeyHashes/getIdentityIdsByPublicKeyHashesFactory.js
lib/methods/platform/waitForStateTransitionResult/WaitForStateTransitionResultResponse.js
lib/test/fixtures/getProofFixture.js
test/unit/methods/platform/getDataContract/GetDataContractResponse.spec.js
test/unit/methods/platform/getDataContract/getDataContractFactory.spec.js
test/unit/methods/platform/getDocuments/GetDocumentsResponse.spec.js
test/unit/methods/platform/getDocuments/getDocumentsFactory.spec.js
test/unit/methods/platform/getIdentitiesByPublicKeyHashes/GetIdentitiesByPublicKeyHashesResponse.spec.js
test/unit/methods/platform/getIdentitiesByPublicKeyHashes/getIdentitiesByPublicKeyHashesFactory.spec.js
test/unit/methods/platform/getIdentitiy/GetIdentityResponse.spec.js
test/unit/methods/platform/getIdentitiy/getIdentityFactory.spec.js
test/unit/methods/platform/getIdentityIdsByPublicKeyHashes/GetIdentityIdsByPublicKeyHashesResponse.spec.js
test/unit/methods/platform/getIdentityIdsByPublicKeyHashes/getIdentityIdsByPublicKeyHashesFactory.spec.js

Need to add ability to requests proofs for platform methods.
Added `prove` option to platform requests. The response includes proof instead of data.
No

feat: add proofs to platform responses

---

lib/methods/core/getTransaction/getTransactionFactory.js

Client crashing when getting transaction info from older dapi nodes
Implemented simple retries for platform method for the case when connecting to a dapi instance that doesn't return metadata. This is a temporary fix and should be removed once proper dapi probing is implemented
Run wallet-lib tests
None

fix: `getTransaction` requested an older DAPI instance

---

CHANGELOG.md
package-lock.json
package.json

Release 0.20.1
- Update changelog
- Bump version to 0.20.0

chore(release): update changelog and bump version 0.20.1

---

lib/methods/platform/getDataContract/GetDataContractResponse.js
lib/methods/platform/getDocuments/GetDocumentsResponse.js
lib/methods/platform/getIdentitiesByPublicKeyHashes/GetIdentitiesByPublicKeyHashesResponse.js
lib/methods/platform/getIdentity/GetIdentityResponse.js
lib/methods/platform/getIdentityIdsByPublicKeyHashes/GetIdentityIdsByPublicKeyHashesResponse.js
lib/methods/platform/response/Proof.js
lib/methods/platform/response/StoreTreeProofs.js
lib/methods/platform/response/createProofFromRawProof.js
lib/methods/platform/waitForStateTransitionResult/WaitForStateTransitionResultResponse.js
lib/test/fixtures/getProofFixture.js
package-lock.json
package.json
test/unit/methods/platform/getDataContract/GetDataContractResponse.spec.js
test/unit/methods/platform/getDataContract/getDataContractFactory.spec.js
test/unit/methods/platform/getDocuments/GetDocumentsResponse.spec.js
test/unit/methods/platform/getDocuments/getDocumentsFactory.spec.js
test/unit/methods/platform/getIdentitiesByPublicKeyHashes/GetIdentitiesByPublicKeyHashesResponse.spec.js
test/unit/methods/platform/getIdentitiesByPublicKeyHashes/getIdentitiesByPublicKeyHashesFactory.spec.js
test/unit/methods/platform/getIdentitiy/GetIdentityResponse.spec.js
test/unit/methods/platform/getIdentitiy/getIdentityFactory.spec.js
test/unit/methods/platform/getIdentityIdsByPublicKeyHashes/GetIdentityIdsByPublicKeyHashesResponse.spec.js
test/unit/methods/platform/getIdentityIdsByPublicKeyHashes/getIdentityIdsByPublicKeyHashesFactory.spec.js
test/unit/methods/platform/waitForStateTransitionResult/waitForStateTransitionResultFactory.spec.js

Support returning multiple store tree proofs
Update dapi-grpc

feat!: support returning multiproof

---

package-lock.json
package.json

Version bumped to 0.21.0-dev.3
In CI
None

chore(release): bump version to 0.21.0-dev.3

---

lib/methods/platform/PlatformMethodsFacade.js
lib/methods/platform/getConsensusParams/ConsensusParamsBlock.js
lib/methods/platform/getConsensusParams/ConsensusParamsEvidence.js
lib/methods/platform/getConsensusParams/getConsensusParamsFactory.js
lib/methods/platform/getConsensusParams/getConsensusParamsResponse.js
package-lock.json
package.json
test/unit/methods/platform/getConsensusParams/ConsensusParamsBlock.spec.js
test/unit/methods/platform/getConsensusParams/ConsensusParamsEvidence.spec.js
test/unit/methods/platform/getConsensusParams/getConsensusParamsFactory.spec.js
test/unit/methods/platform/getConsensusParams/getConsensusParamsResponse.spec.js

Need to implement getConsensusParams method to get current consensus params from tenderdash
Implemented new getConsensusParams method
With platform-test-suite
No

feat: implement getConsensusParams method

---

package-lock.json
package.json

grpc-common version was updated
Update grpc-common dep versions
In CI

chore: update grpc-common deps

---

package-lock.json
package.json

Need to update DPP to the latest version
DPP was updated to 0.21.0-dev.2
Unit tests
No

feat: update DPP to 0.21.0-dev.2

---

package.json

The `check-package` script was not removed after the migration from Travis
Remove `check-package` script
In CI
None

chore: remove unused check-package script

---

.github/workflows/test_and_release.yml
package-lock.json
package.json

We need to update to node 16
- Update package to node 16
- Run tests
- Update CI
In CI
None

chore: update to node 16

---

package-lock.json
package.json

Bump version for release
Bump version to  v0.21.0 dev.9

chore: bump version to v0.21.0 dev.9

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.10
In CI
None

chore: bump version to 0.21.0-dev.10

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.12
In CI
None

chore: bump version to 0.21.0-dev.12

---

lib/transport/GrpcTransport/createGrpcTransportError.js

Empty `drive-error-data-bin` in metadata throws an error 
- Do not decode empty metadata
None
None

fix: empty `drive-error-data-bin` throws an error

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.13
In CI
None

chore: bump version to 0.21.0-dev.13

---

CHANGELOG.md
package-lock.json
package.json

Release 0.21.3
- Update changelog
- Bump version to 0.21.3
None
None

chore(release): update changelog and bump version to 0.21.3
