dashevo/js-dapi-client

package-lock.json, package.json, src/index.js
This PR enhances getBlockHeaders enpoint with optional verbose param, default = false, in order to get the serialized version of the headers which saves a lot of space and speeds up header download ~ 2.5x. Especially useful if downloading a lot of headers at the same time.
Also set `limit` default to 1 to cause less stress on resources when not set explicitly.
Cf. https://github.com/dashevo/dapi/pull/171
=> Enhance `getBlockHeaders` endpoint with optional verbose param

package-lock.json, package.json, src/index.js, test/integration/api/index.js, test/perf/async_api_per_node.js, test/src/index.js
**Issue being fixed or implemented**
methods getTransaction and getTransactionById with the same functionality
**What was done**
removed getTransaction, getTransactionById remained because:
- getTransaction calles getTransactionById
- in dapi rpc method is with the same name getTransactionById
- getTransaction almost never used in the tests
**What has been tested**
unit and integration tests passed
**What needs to be tested**
nothing.
=> Remove getTransaction which duplicates getTransactionById

test/integration/api/index.js, test/integration/e2e/index.js, test/integration/features/index.js
**Issue being fixed or implemented**
- use profile instead of user in dpp.document
- removeMetadata before stPacket creation
- fix 'rate limited free transaction' when we can't send trxs with last x*10(enough big kB amount) inputs without fee
**What was done**
- use profile for dpp.document
- removeMetadata before stPacket creation and responses' verification
- update test to verify 'rate limited free transaction' when we can't send trxs with last x*10(enough big kB amount) inputs without fee, but with fee we can send transaction with x*10 inputs
**What has been tested**
integration tests passed
**What needs to be tested**
nothing.
=> Update functional and e2e tests to the new DPP version

package-lock.json, package.json
Quorum had an old version of `dashcore-lib`. Which is now updated in `@dashevo/quorums`.
This PR just bump the reference of the version.
- bumped quorums version
The package-lock.json file has been deleted and re-generated by NPM, if there was some fixed element (did not found any but still taking note on it), one might want to be careful before merging this one.
=> Bumped quorums package to 1.0.5

.travis.yml
This fixes `Failed to replace env in config: ${NPM_TOKEN}` error during Travis build.
=> Use `npm config` command for Travis build setup

package-lock.json, package.json, src/index.js, test/src/index.js
Implement basic Core DAPI endpoints:
- `getBlock`
- `getStatus`
- `getTransaction`
- `sendTransaction`
- `getBlockByHeight`
- `getBlockByHash`
BREAKING CHANGES: previous `sendRawTransaction` is now called `sendTransaction`
=> feat: implement basic Core endpoints

src/index.js
There are some inconsistencies in our jsdoc comments. I made the following changes to help with some basic doc auto-generation I am investigating. 
This PR fixes the minor whitespace/naming inconsistency in `src/index.js`. It also moves the class jsdoc as suggested [here](https://github.com/documentationjs/documentation/blob/master/docs/RECIPES.md#classes) (results in much cleaner output from documentation.js which I have been using to auto-generate [some documentation for evaluation](https://thephez.github.io/dapi-client-documentation.js/#dapiclient)).
No code changes to test
=> doc: jsdoc formatting

src/RPCClient.js, src/errors/RPCError.js, src/transport/GrpcTransport.js, src/transport/JsonRpcTransport.js, test/src/index.js
- JSON RPC transport now retries requests to a different masternode in case of internal error and any server error
- gRPC transport now retries request to a different masternode  in case of any HTTP error received
- Error codes -32603 and a range of -32000 to -32099 are checked in JSON RPC transport
- Error code `CANCELLED` is checked in gRPC transport (which is thrown in case of any HTTP error)
Tested using `mn-bootstrap` running custom pre-built image of `dapi` that is throwing errors in case of JSON RPC and returning HTTP error using NGINX in case of gRPC.
None
=> feat: more types of errors to retry

lib/transport/GrpcTransport.js, test/unit/transport/GrpcTransport.spec.js
Using new `dapi-grpc`, passing `options` to every gRPC request, and using simplified URL.
- gRPC request is called with empty `meta` object, and `options` are being passed to every request
- URL passed as is, only `port` is different now
Unit tests.
None.
=> feat: timeout options for gRPC requests and simplified URL for gRPC client

lib/networkConfigs.js, test/unit/DAPIClient.spec.js
Construct DAPIClient with network option didn't work properly
Fixed local network config. Added new test.
Unit test
No
=> fix: construct DAPIClient with local network option didn't work properly

lib/DAPIClient.js, test/unit/DAPIClient.spec.js
Default timeout was increased to 10 seconds, as a temporary solution for breaking tests
Default timeout was increased to 10 seconds
=> fix: 2 seconds timeout not enough for some requests

lib/methods/core/subscribeToTransactionsWithProofsFactory.js, test/unit/methods/core/subscribeToTransactionsWithProofsFactory.spec.js
The default client timeout shouldn't apply to gRPC streams, otherwise, the client just hangs when the timeout is reached. 
Set default timeout for stream method to `undefined`. It will overwrite default client options but we still can set it deadline in method options if we need it.
Unit test implemented.
Now streaming methods do not hang when the client timeout is reached.
=> fix: global default timeout applies for streams

src/transport/JsonRpcTransport.js
This is a hotfix for retry logic. We should retry on `ETIMEDOUT` status.
Added `ETIMEDOUT` to a list of errors to retry.
Unit tests.
None.
=> fix: JSON RPC doesn't retry on `ETIMEDOUT`

README.md, lib/DAPIClient.js, lib/dapiAddressProvider/createDAPIAddressProviderFromOptions.js, lib/networkConfigs.js, test/unit/DAPIClient.spec.js, test/unit/dapiAddressProvider/createDAPIAddressProviderFromOptions.spec.js
There is an ambiguity in option name - `addresses`
Renamed option to `dapiAddresses`
Tests.
`addresses` `DAPIClient` option is now called `dapiAddresses`
=> fix: ambiguity in `addresses` option

README.md, lib/dapiAddressProvider/DAPIAddress.js, test/unit/dapiAddressProvider/DAPIAddress.spec.js
Passing not just host but ports as part of the string address string representation will be very convenient for usage.
* Parse HTTP and gRPC ports from address string.
* Add `DAPIAddress#toString` that returns the address string representation.
None
=> feat: add ports to string representation of DAPIAddress

lib/methods/core/subscribeToTransactionsWithProofsFactory.js, test/unit/methods/core/subscribeToTransactionsWithProofsFactory.spec.js
Internal error is thrown when `options.fromBlockHeight` is submitted as `0` to `subscribeToTransactionsWithProofs`
Added assertions for `fromBlockHeight` value to be more then 0
Unit tests.
None.
=> fix: internal error when submitting `fromBlockHeight` as 0 to `subscribeToTransactionsWithProofs`

lib/methods/core/broadcastTransactionFactory.js, lib/methods/platform/broadcastStateTransitionFactory.js, package-lock.json, package.json, test/integration/methods/core/CoreMethodsFacade.spec.js, test/integration/methods/platform/PlatformMethodsFacade.spec.js, test/unit/methods/core/broadcastTransactionFactory.spec.js, test/unit/methods/platform/broadcastStateTransitionFactory.spec.js
In order to more accurately name DAPI and DAPI gRPC endpoints we need to rename sendTransaction and applyStateTransition methods.
dapi-grpc updated to 0.15.0-dev.1
Updated dapi-grpc class names
Updated DAPI method names
Unit tests
This version is incompatible with DAPI and dapi-grpc lover than 0.15.0-dev-1
=> feat!: rename sendTransaction and applyStateTransition to broadcast

lib/transport/GrpcTransport.js, test/unit/transport/GrpcTransport.spec.js
When a client make a request that doesn’t support a specific gRPC service version (DAPI has outdated version) it won’t be able to do that due unknown gRPC service name requested by the client, therefore we want to try another one.
- feat: Request retry on UNIMPLEMENTED
- added unit test. 
- adding additional test in test-suite
N/A
=> feat: retry request on UNIMPLEMENTED error

lib/methods/platform/getDataContractFactory.js, lib/methods/platform/getDocumentsFactory.js, lib/methods/platform/getIdentityFactory.js, package-lock.json, package.json, test/unit/methods/platform/getDataContractFactory.spec.js, test/unit/methods/platform/getDocumentsFactory.spec.js, test/unit/methods/platform/getIdentityFactory.spec.js
convert objects inherited from Buffer to pure buffer as google protobuf doesn't support extended buffers https://github.com/protocolbuffers/protobuf/blob/master/js/binary/utils.js#L1049
Check if an object is exteneded from a buffer and clone its contents to a base buffer
run tests
none
=> fix: extended buffers can't be converted to UInt8Array

lib/methods/platform/getIdentitiesByPublicKeyHashesFactory.js, lib/methods/platform/getIdentityIdsByPublicKeyHashesFactory.js
Invalid types were returned by new methods
Wrap result using `Buffer#from`
Unit tests.
None.
=> fix: return `Buffer` instead of `Uint8Array`

lib/methods/platform/broadcastStateTransitionFactory.js
`broadcastStateTransition` is timing out on testnet and larger networks
Overwrite default timeout for `broadcastStateTransition`
Broadcasting transactions
None
=> fix: broadcastStateTransition is timing out on testnet

package-lock.json, package.json
Packages depending on `js-dapi-client` have been throwing scary-looking warnings to end users like below:
```
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```
This PR updates the axios dependency to fix the vulnerability (as described at [axios/axios#3410](https://github.com/axios/axios/pull/3410))
Bump axios version in `package.json` and run `npm i` to update `package-lock.json`
`npm run test` all tests passing
None known
=> fix: critical security vulnerability in axios@0.19.2

lib/dapiAddressProvider/ListDAPIAddressProvider.js
Platform test suite not working on mac os due to local network docker setup binding to a different IP
Add check if the network is regtest replace dapi addresses with localhost, so all network calls will be rerouted through localhost for tests on mac os
Run platform test suite with that dapi-client
None?
=> feat: replace all MN addresses with localhost is the network is local

package-lock.json, package.json
Updated `dapi-grpc` dependency with fixed type for `height` in `Metadata`
- updated `dapi-grpc`
None.
=> fix: metadata height type was uint32 instead of int64

lib/methods/platform/broadcastStateTransition/broadcastStateTransitionFactory.js, lib/methods/platform/getDataContract/getDataContractFactory.js, lib/methods/platform/getDocuments/getDocumentsFactory.js, lib/methods/platform/getIdentitiesByPublicKeyHashes/getIdentitiesByPublicKeyHashesFactory.js, lib/methods/platform/getIdentity/getIdentityFactory.js, lib/methods/platform/getIdentityIdsByPublicKeyHashes/getIdentityIdsByPublicKeyHashesFactory.js, lib/methods/platform/waitForStateTransitionResult/waitForStateTransitionResultFactory.js, package.json
Implemented simple retries for platform method for the case when connecting to a dapi instance that doesn't return metadata. This is a temporary fix and should be removed once proper dapi probing is implemented
Implement naive cycle retry in every platform method as a temporary fix
Run the wallet-lib tests
None
=> fix: crash when connecting to an older version of dapi

lib/transport/GrpcTransport/createGrpcTransportError.js
createConsensusError can be called with empty arguments if arguments field is empty
Fixed createConsensusError function
With tests
No
=> fix: createConsensusError can be called with empty arguments

lib/transport/GrpcTransport/createGrpcTransportError.js, package-lock.json, package.json, test/unit/transport/GrpcTransport/createGrpcTransportError.spec.js
createGrpcTransportError can't get metadata from gRPC Error in browser environment
createGrpcTransportError method fixed
Unit tests
No
=> fix: createGrpcTransportError can't get metadata in browser environment

lib/transport/JsonRpcTransport/createJsonTransportError.js, lib/transport/JsonRpcTransport/errors/WrongHttpCodeError.js, lib/transport/JsonRpcTransport/requestJsonRpc.js, test/unit/transport/JsonRpcTransport/requestJsonRpc.spec.js
Dapi-client doesn't retry on 502 errors
Fixed JsonTransport in Dapi-client
Platform test suite
No
=> fix: retry doesn’t work with 502 errors
